name: Playwright Framework
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-focal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright tests"
          npm run test:ci
      - name: Use Java
        uses: actions/checkout@v3
        uses: actions/setup-java@v3
        with:
          version: '13'
          architecture: x64
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: test-results
      - name: Generate report
        run: npm run test:report