name: Playwright Framework
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-focal
    steps:
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright tests"
          npm run test:ci
          echo "Generate reports"
          npm run test:report
      - name: Use Java
        uses: actions/checkout@v3
        with:
          version: '13'
          architecture: x64
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: test-results